[tool.poetry]
name = "rsa"
version = "0.1.0"
description = ""
authors = ["Marvin Theiss <marvin.theiss@psychol.uni-giessen.de>"]
readme = "README.md"

[tool.poetry.dependencies]
hydra-core = "^1.3.2"
jupyterlab = "^4.1.2"
matplotlib = "^3.8.3"
numpy = "^1.26.4"
python = "^3.11"
tensorboard = "^2.16.2"
torch = "^2.2.0"
torchvision = "^0.17.0"
tqdm = "^4.66.2"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
