[tool.poetry]
name = "src"
version = "0.1.0"
description = ""
authors = ["Marvin Theiss <marvin.theiss@psychol.uni-giessen.de>"]
readme = "README.md"

[tool.poetry.dependencies]
hydra-core = "^1.3.2"
jupyterlab = "^4.1.2"
matplotlib = "^3.8.3"
numpy = "^1.26.4"
# https://github.com/tensorflow/tensorboard/issues/6808
# https://github.com/tensorflow/tensorboard/commit/e795312f70537cb9c9ab4bd2a08a03e77f0356a5
protobuf = ">=3.19.6,!=4.24.0,<5.0.0"
python = "^3.12"
scipy = "^1.13.0"
tbparse = "^0.0.8"
tensorboard = "^2.16.2"
torch = "^2.3.0"
torchmetrics = "^1.3.2"
torchvision = "^0.18.0"
tqdm = "^4.66.2"


[tool.poetry.group.dev.dependencies]
pylint = "^3.2.2"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

