# https://pytorch.org/docs/2.4/generated/torch.optim.Adam.html
name: Adam
lr: 0.001
betas: [0.9, 0.999]
weight_decay: 0
kwargs:
  _target_: torch.optim.adam.Adam
  lr: ${optimizer.lr}
  betas: ${optimizer.betas}
  eps: 1e-8
  weight_decay: ${optimizer.weight_decay}
  amsgrad: false
  foreach: null
  maximize: false
  capturable: false
  differentiable: false
  fused: null
