# https://pytorch.org/docs/2.3/generated/torch.optim.Adam.html
name: Adam
_target_: torch.optim.adam.Adam
params: ???
lr: 1e-3
betas: [0.9, 0.999]
eps: 1e-8
weight_decay: 0
amsgrad: False
foreach: null
maximize: false
capturable: false
differentiable: false
fused: null
