# https://pytorch.org/docs/2.4/generated/torch.optim.lr_scheduler.CosineAnnealingLR.html
name: CosineAnnealingLR
kwargs:
  _target_: torch.optim.lr_scheduler.CosineAnnealingLR
  T_max: ???
  eta_min: 0
  last_epoch: -1
