# https://pytorch.org/docs/2.4/generated/torch.optim.lr_scheduler.StepLR.html
name: StepLR
lr_step_size: ???
lr_gamma: 0.1

kwargs:
  _target_: torch.optim.lr_scheduler.StepLR
  step_size: ${main_scheduler.lr_step_size}
  gamma: ${main_scheduler.lr_gamma}
  last_epoch: -1
