# https://optuna.readthedocs.io/en/v4.0.0/reference/generated/optuna.pruners.MedianPruner.html
name: MedianPruner
n_startup_trials: 5
n_warmup_steps: 0
n_min_trials: 1

kwargs:
  _target_: optuna.pruners._median.MedianPruner
  n_startup_trials: ${optuna.pruner.n_startup_trials}
  n_warmup_steps: ${optuna.pruner.n_warmup_steps}
  interval_steps: 1
  n_min_trials: ${optuna.pruner.n_min_trials}
