# https://optuna.readthedocs.io/en/v4.0.0/reference/generated/optuna.pruners.MedianPruner.html
# NOTE: The ``n_warmup_steps`` parameter behaves differently to how it is described in the official
#       documentation.  Here, it specifies the number of steps that have to be completed before the
#       first pruning check is performed.  See the ``BaseTrainer`` class for an explanation of why
#       this is the case.
name: MedianPruner
n_startup_trials: 5
n_warmup_steps: 0
interval_steps: 1
n_min_trials: 1

kwargs:
  _target_: optuna.pruners._median.MedianPruner
  n_startup_trials: ${optuna.pruner.n_startup_trials}
  n_warmup_steps: ${optuna.pruner.n_warmup_steps}
  interval_steps: ${optuna.pruner.interval_steps}
  n_min_trials: ${optuna.pruner.n_min_trials}
