name: lenet
architecture:
  _target_: models.lenet.LeNet
  num_classes: ${dataset.num_classes}
preprocessing:
  _target_: torchvision.transforms.v2.Compose
  transforms:
    - _target_: torchvision.transforms.v2.Resize
      size: 32
      interpolation: 2  # BILINEAR
      antialias: True
    - _target_: torchvision.transforms.v2.Grayscale
    - _target_: torchvision.transforms.v2.ToImage
    - _target_: utils.to_dtype_wrapper.ToDtypeWrapper
      dtype: float32
      scale: True
    - _target_: torchvision.transforms.v2.Normalize
      mean: ${dataset.norm_constants.mean}
      std: ${dataset.norm_constants.std}
