name: LeNetColor
input_size: 32
layer_widths: [6, 16, 120, 84]
load_weights_from: null
evaluate_on: null

kwargs:
  _target_: models.lenet_color.LeNetColor
  layer_widths: ${model.layer_widths}
  num_classes: ${dataset.num_classes}
