name: lenet
architecture:
  _target_: models.LeNet
  num_classes: ${dataset.num_classes}
norm_constants:
  # Computed on FashionMNIST dataset (training set, batch size 32)
  mean: [0.285556]
  std: [0.338484]
preprocessing:
  _target_: torchvision.transforms.v2.Compose
  transforms:
    - _target_: torchvision.transforms.v2.Resize
      size: 32
      interpolation: 2  # BILINEAR
      antialias: True
    - _target_: torchvision.transforms.v2.Grayscale
    - _target_: torchvision.transforms.v2.ToImage
    - _target_: utils.ToDtypeWrapper
      dtype: float32
      scale: True
    - _target_: torchvision.transforms.v2.Normalize
      mean: ${model.norm_constants.mean}
      std: ${model.norm_constants.std}
