architecture:
  _target_: models.VGG
  num_layers: 11  # one of [11, 13, 16, 19]
  num_classes: ${dataset.num_classes}
preprocessing:
  _target_: torchvision.transforms.v2.Compose
  transforms:
    - _target_: torchvision.transforms.v2.Resize
      size: 256
      interpolation: 2  # BILINEAR
      antialias: True
    - _target_: torchvision.transforms.v2.CenterCrop
      size: 224
    - _target_: torchvision.transforms.v2.ToImage
    - _target_: utils.ToDtypeWrapper
      dtype: float32
      scale: True
    - _target_: torchvision.transforms.v2.Normalize
      mean: ${dataset.stats.mean}
      std: ${dataset.stats.std}
