name: VGG
input_size: 224
num_layers: ???
pretrained: ???
load_weights_from: null
evaluate_on: null

kwargs:
  _target_: models.vgg.VGG
  num_layers: ${model.num_layers}
  num_classes: ${dataset.num_classes}
  pretrained: ${model.pretrained}
