name: vgg11
architecture:
  _target_: models.vgg.VGG
  num_layers: 11
  num_classes: ${dataset.num_classes}
  pretrained: False
preprocessing:
  _target_: torchvision.transforms.v2.Compose
  transforms:
    - _target_: torchvision.transforms.v2.Resize
      size: 256
      interpolation: 2  # BILINEAR
      antialias: True
    - _target_: torchvision.transforms.v2.CenterCrop
      size: 224
    - _target_: torchvision.transforms.v2.ToImage
    - _target_: utils.to_dtype_wrapper.ToDtypeWrapper
      dtype: float32
      scale: True
    - _target_: torchvision.transforms.v2.Normalize
      mean: ${dataset.norm_constants.mean}
      std: ${dataset.norm_constants.std}
