name: vgg16
architecture:
  _target_: models.VGG
  num_layers: 16
  num_classes: ${dataset.num_classes}
  pretrained: False
# Cf. https://pytorch.org/vision/stable/models/generated/torchvision.models.vgg16.html
norm_constants:
  mean: [0.485, 0.456, 0.406]
  std: [0.229, 0.224, 0.225]
preprocessing:
  _target_: torchvision.transforms.v2.Compose
  transforms:
    - _target_: torchvision.transforms.v2.Resize
      size: 256
      interpolation: 2  # BILINEAR
      antialias: True
    - _target_: torchvision.transforms.v2.CenterCrop
      size: 224
    - _target_: torchvision.transforms.v2.ToImage
    - _target_: utils.ToDtypeWrapper
      dtype: float32
      scale: True
    - _target_: torchvision.transforms.v2.Normalize
      mean: ${model.norm_constants.mean}
      std: ${model.norm_constants.std}
