# https://pytorch.org/docs/2.4/generated/torch.optim.lr_scheduler.ConstantLR.html
name: ConstantLR
warmup_decay: ???
warmup_epochs: ???

kwargs:
  _target_: torch.optim.lr_scheduler.ConstantLR
  factor: ${warmup_scheduler.warmup_decay}
  total_iters: ${warmup_scheduler.warmup_epochs}
  last_epoch: -1
