# https://pytorch.org/docs/2.4/generated/torch.optim.lr_scheduler.LinearLR.html
name: LinearLR
warmup_decay: 0.3333333333333333
warmup_epochs: 5

kwargs:
  _target_: torch.optim.lr_scheduler.LinearLR
  start_factor: ${warmup_scheduler.warmup_decay}
  end_factor: 1.0
  total_iters: ${warmup_scheduler.warmup_epochs}
  last_epoch: -1
