name: cifar10
num_classes: 10
is_grayscale: False
norm_constants:
  # Computed on training set
  mean: [0.4914, 0.4822, 0.4465]
  std: [0.2023, 0.1994, 0.201]
train_set:
  _target_: datasets.cifar10.CIFAR10
  data_dir: ${paths.data}
  train: True
  load_into_memory: True
  transform: ${model.preprocessing}
test_set:
  _target_: datasets.cifar10.CIFAR10
  data_dir: ${paths.data}
  train: False
  load_into_memory: True
  transform: ${model.preprocessing}
