name: CIFAR10
num_classes: 10
is_grayscale: false
stats:
  mean: [0.4914, 0.4822, 0.4465]
  std: [0.2023, 0.1994, 0.201]

train_set:
  _target_: datasets.cifar10.CIFAR10
  data_dir: "../data"
  train: true
  load_into_memory: false

test_set:
  _target_: datasets.cifar10.CIFAR10
  data_dir: "../data"
  train: false
  load_into_memory: false
