name: CIFAR10
num_classes: 10
is_grayscale: False
transform_train:
  # Normalization constants computed on training set
  mean: [0.4914, 0.4822, 0.4465]
  std: [0.2023, 0.1994, 0.201]
  crop_size: ${model.input_size}
  crop_scale:
    lower: 1.0
    upper: 1.0
  crop_ratio:
    lower: 1.0
    upper: 1.0
  flip_prob: 0.0
transform_val:
  mean: ${dataset.transform_train.mean}
  std: ${dataset.transform_train.std}
  resize_size: ???
  crop_size: ${model.input_size}
train_set:
  _target_: datasets.cifar10.CIFAR10
  data_dir: ${paths.data}
  train: True
  load_into_memory: True
test_set:
  _target_: datasets.cifar10.CIFAR10
  data_dir: ${paths.data}
  train: False
  load_into_memory: True
