name: cifar10
num_classes: 10
is_grayscale: False
transform_params:
  # Normalization constants computed on training set
  mean: [0.4914, 0.4822, 0.4465]
  std: [0.2023, 0.1994, 0.201]
  crop_size: ${model.input_size}
  crop_scale:
    lower: ???
    upper: ???
  resize_size: ???
  flip_prob: 0.5
train_set:
  _target_: datasets.cifar10.CIFAR10
  data_dir: ${paths.data}
  train: True
  load_into_memory: True
test_set:
  _target_: datasets.cifar10.CIFAR10
  data_dir: ${paths.data}
  train: False
  load_into_memory: True
