name: cifar10
num_classes: 10
is_grayscale: False
norm_constants:
  # Computed on training set
  mean: [0.4910, 0.4819, 0.4465]
  std: [0.2021, 0.1993, 0.2009]
train_set:
  _target_: datasets.cifar10.CIFAR10
  data_dir: ${paths.data}
  train: True
  transform: ${model.preprocessing}
test_set:
  _target_: datasets.cifar10.CIFAR10
  data_dir: ${paths.data}
  train: False
  transform: ${model.preprocessing}
