name: fashionmnist
num_classes: 10
is_grayscale: True
norm_constants:
  # Computed on training set
  mean: [0.2860]
  std: [0.3205]
train_set:
  _target_: datasets.FashionMNIST
  root: ${paths.data}
  train: True
  transform: ${model.preprocessing}
val_set:
  _target_: datasets.FashionMNIST
  root: ${paths.data}
  train: False
  transform: ${model.preprocessing}
