name: fashionmnist
num_classes: 10
is_grayscale: True
norm_constants:
  # Computed on training set
  mean: [0.2860]
  std: [0.3205]
train_set:
  _target_: datasets.fashionmnist.FashionMNIST
  data_dir: ${paths.data}
  train: True
  load_into_memory: True
  transform: ${model.preprocessing}
test_set:
  _target_: datasets.fashionmnist.FashionMNIST
  data_dir: ${paths.data}
  train: False
  load_into_memory: True
  transform: ${model.preprocessing}
