name: FashionMNIST
num_classes: 10
is_grayscale: True
transform_train:
  # Normalization constants computed on training set
  mean: [0.2860]
  std: [0.3205]
  crop_size: ${model.input_size}
  crop_scale:
    lower: 1.0
    upper: 1.0
  crop_ratio:
    lower: 1.0
    upper: 1.0
  flip_prob: 0.0
  ta_wide: False
  random_erase_prob: 0.0
transform_val:
  mean: ${dataset.transform_train.mean}
  std: ${dataset.transform_train.std}
  resize_size: ???
  crop_size: ${model.input_size}
train_set:
  _target_: datasets.fashionmnist.FashionMNIST
  data_dir: ${paths.data}
  train: True
  load_into_memory: True
test_set:
  _target_: datasets.fashionmnist.FashionMNIST
  data_dir: ${paths.data}
  train: False
  load_into_memory: True
