name: fashionmnist
num_classes: 10
is_grayscale: True
transform_params:
  # Normalization constants computed on training set
  mean: [0.2860]
  std: [0.3205]
  crop_size: ${model.input_size}
  crop_scale:
    lower: ???
    upper: ???
  resize_size: ???
  flip_prob: 0.5
train_set:
  _target_: datasets.fashionmnist.FashionMNIST
  data_dir: ${paths.data}
  train: True
  load_into_memory: True
test_set:
  _target_: datasets.fashionmnist.FashionMNIST
  data_dir: ${paths.data}
  train: False
  load_into_memory: True
