name: FashionMNIST
num_classes: 10
is_grayscale: true
stats:
  mean: [0.2860]
  std: [0.3205]

train_set:
  _target_: datasets.fashionmnist.FashionMNIST
  data_dir: "../data"
  train: true
  load_into_memory: false

test_set:
  _target_: datasets.fashionmnist.FashionMNIST
  data_dir: "../data"
  train: false
  load_into_memory: false
