num_classes: 10
train_set:
  _target_: datasets.FashionMNIST
  root: ${paths.data}
  train: True
  transform: ${model.preprocessing}
val_set:
  _target_: datasets.FashionMNIST
  root: ${paths.data}
  train: False
  transform: ${model.preprocessing}
