train:
  _target_: torchvision.datasets.FashionMNIST
  root: ${paths.data}
  train: True
  transform:
    _target_: torchvision.transforms.v2.Compose
    transforms:
      - _target_: torchvision.transforms.v2.ToImage
      - _target_: src.utils.to_dtype_wrapper.ToDtypeWrapper
        dtype: float32
        scale: True
      - _target_: torchvision.transforms.v2.Normalize
        mean: [0.5]
        std: [0.5]
  download: True
val:
  _target_: torchvision.datasets.FashionMNIST
  root: ${paths.data}
  train: False
  transform: ${dataset.train.transform}
  download: True