name: ImageNet
num_classes: 1000
is_grayscale: false

transform_train:
  mean: [0.485, 0.456, 0.406]
  std: [0.229, 0.224, 0.225]
  crop_size: ${model.input_size}
  crop_scale:
    lower: 1.0  # PyTorch default (RandomResizedCrop): 0.08
    upper: 1.0  # PyTorch default (RandomResizedCrop): 1.0
  crop_ratio:
    lower: 1.0  # PyTorch default (RandomResizedCrop): 0.75
    upper: 1.0  # PyTorch default (RandomResizedCrop): 4/3
  flip_prob: 0.0
  ta_wide: false
  random_erase_prob: 0.0  # PyTorch default (RandomErasing): 0.5
  mixup_alpha: 0.0  # PyTorch default (MixUp): 1.0
  cutmix_alpha: 0.0  # PyTorch default (CutMix): 1.0

transform_val:
  mean: ${dataset.transform_train.mean}
  std: ${dataset.transform_train.std}
  resize_size: ???
  crop_size: ${model.input_size}

train_set:
  _target_: datasets.imagenet.ImageNet
  data_dir: "../data"
  train: true

test_set:
  _target_: datasets.imagenet.ImageNet
  data_dir: "../data"
  train: false
