name: ImageNet
num_classes: 1000
is_grayscale: false
stats:
  mean: [0.485, 0.456, 0.406]
  std: [0.229, 0.224, 0.225]

train_set:
  _target_: datasets.imagenet.ImageNet
  data_dir: "../data"
  train: true

test_set:
  _target_: datasets.imagenet.ImageNet
  data_dir: "../data"
  train: false
