num_classes: 1000
stats:
  mean: [0.5, 0.5, 0.5]
  std: [0.5, 0.5, 0.5]
raw_set:
  _target_: datasets.ImageNet
  root: ${paths.data}
  train: True
  transform:
    _target_: torchvision.transforms.v2.Compose
    transforms:
      - _target_: torchvision.transforms.v2.ToImage
      - _target_: utils.ToDtypeWrapper
        dtype: float32
        scale: True
train_set:
  _target_: datasets.ImageNet
  root: ${paths.data}
  train: True
  transform: ${model.preprocessing}
val_set:
  _target_: datasets.ImageNet
  root: ${paths.data}
  train: False
  transform: ${dataset.train_set.transform}
