num_classes: 1000
train_set:
  _target_: datasets.ImageNet
  root: ${paths.data}
  train: True
  transform: ${model.preprocessing}
val_set:
  _target_: datasets.ImageNet
  root: ${paths.data}
  train: False
  transform: ${model.preprocessing}
