name: ImageNet
num_classes: 1000
is_grayscale: False
transform_train:
  # https://pytorch.org/vision/0.19/models/generated/torchvision.models.alexnet.html
  mean: [0.485, 0.456, 0.406]
  std: [0.229, 0.224, 0.225]
  crop_size: ${model.input_size}
  crop_scale:
    lower: 1.0
    upper: 1.0
  crop_ratio:
    lower: 1.0
    upper: 1.0
  flip_prob: 0.0
  ta_wide: False
  random_erase_prob: 0.0
  mixup_alpha: 0.0
  cutmix_alpha: 0.0
transform_val:
  mean: ${dataset.transform_train.mean}
  std: ${dataset.transform_train.std}
  resize_size: ???
  crop_size: ${model.input_size}
train_set:
  _target_: datasets.imagenet.ImageNet
  data_dir: ${paths.data}
  train: True
test_set:
  _target_: datasets.imagenet.ImageNet
  data_dir: ${paths.data}
  train: False
