name: ImageNet
num_classes: 1000
is_grayscale: False
transform_params:
  # https://pytorch.org/vision/0.19/models/generated/torchvision.models.alexnet.html
  mean: [0.485, 0.456, 0.406]
  std: [0.229, 0.224, 0.225]
  crop_size: ${model.input_size}
  crop_scale:
    lower: 1.0
    upper: 1.0
  crop_ratio:
    lower: 1.0
    upper: 1.0
  resize_size: ???
  flip_prob: 0.0
train_set:
  _target_: datasets.imagenet.ImageNet
  data_dir: ${paths.data}
  train: True
test_set:
  _target_: datasets.imagenet.ImageNet
  data_dir: ${paths.data}
  train: False
