defaults:
  - model: ???
  - dataset: ???
  - criterion: cross_entropy
  - override hydra/job_logging: disabled
  - override hydra/hydra_logging: disabled
  - _self_


# ---------------
# REPRODUCIBILITY
# ---------------

reproducibility:
  split_seed: 42  # controls split of the dataset into training and validation sets


# ----------------
# MODEL EVALUATION
# ----------------

model:
  load_weights_from: ???
  evaluate_on: test  # either "train", "val", or "test"


# ------------
# DATA LOADING
# ------------

dataset:
  transform_val:
    resize_size: ${model.input_size}

dataloader:
  val_split: 0.20  # fraction of the dataset to use as validation set
  batch_size: 32
  num_workers: 4


# -------------------
# PERFORMANCE METRICS
# -------------------

metrics:
  Accuracy@1:
    _target_: torchmetrics.classification.MulticlassAccuracy
    num_classes: ${dataset.num_classes}
    top_k: 1
    average: micro
    multidim_average: global
  Accuracy@5:
    _target_: torchmetrics.classification.MulticlassAccuracy
    num_classes: ${dataset.num_classes}
    top_k: 5
    average: micro
    multidim_average: global


# --------------
# HYDRA SETTINGS
# --------------

hydra:
  output_subdir: null
  run:
    dir: .
