defaults:
  - criterion: cross_entropy
  - dataset: fashionmnist
  - model: lenet
  - optimizer: sgd
  - _self_
run: train_classifier/${model.name}/${dataset.name}/${now:%Y-%m-%d_%H-%M-%S}
paths:
  data: ../data
  logs: ../logs/${run}
  checkpoint: null  # checkpoint to resume training from, null to start training from scratch
hydra:
  run:
    dir: ${paths.logs}
dataloader:
  val_split: 0.15  # fraction of the training set to use as validation set
  split_seed: 23  # controls random split of the dataset into training and validation sets
  shuffle_seed: 41  # controls shuffling of the training set
  batch_size: 32
  num_workers: 0
training:
  seed: 42
  num_epochs: 100
metrics:  # empty dict ``{}`` to disable tracking of additional metrics
  MulticlassAccuracy:
    _target_: torchmetrics.classification.MulticlassAccuracy
    num_classes: ${dataset.num_classes}
    top_k: 1
    average: micro
    multidim_average: global
performance:
  metric: Loss  # either "Loss" or one of the keys in the ``metrics`` dict
  higher_is_better: False
  dataset: Val  # either "Train" or "Val"
  patience: 10  # null to disable early stopping
  keep_previous_best_score: True
checkpoints:
  dir: ../checkpoints/${run}
  save_frequency: 10  # null to disable regular checkpoint saves
  save_best_model: True
  delete_previous: True
tensorboard:
  updates_per_epoch:
    Train: 10  # null to disable TensorBoard logging during training
    Val: 10  # null to disable TensorBoard logging during validation
