defaults:
  - model: lenet
  - dataset: fashionmnist
  - optional model/dataset: ${model}_${dataset}
  - loss: cross_entropy
  - optimizer: sgd
  - optional optimizer/model: ${optimizer}_${model}
  - _self_
paths:
  data: ../data
  logs: ../logs/train_classifier/${model.name}/${dataset.name}/${now:%Y-%m-%d_%H-%M-%S}
hydra:
  run:
    dir: ${paths.logs}
dataloader:
  batch_size: 32
  num_workers: 16
training:
  num_epochs: 90
  log_frequency: 10
  seed: 42
